import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../comps/Navbar';
import Footer from '../comps/Footer';
import { useState } from 'react';
import Image from 'next/image';

export default function Contact() {
	const [names, setNames] = useState('');
	const [email, setEmail] = useState('');
	const [message, setMessage] = useState('');
	const handleSubmit = (e) => {
		e.preventDefault();
		setNames('');
		setEmail('');
		setMessage('');
	};
	return (
		<>
			<Head>
				<title>EatUp | Contact </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />

			<section className=' container mx-auto md:flex mt-16'>
				<div className='contact'>
					<h2 className='text-center font-bold text-3xl font-mono mb-8'>
						Get in Touch
					</h2>
					<p className='leading-8'>
						Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet
						quibusdam ab totam quia consequuntur officia maxime ratione tenetur,
						atque labore voluptatem harum quos voluptatum laudantium. Soluta,
						obcaecati optio. Eaque, amet?
					</p>
					<p className='leading-8'>
						Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet
						quibusdam ab totam quia consequuntur officia maxime ratione tenetur,
						atque labore voluptatem harum quos voluptatum laudantium. Soluta,
						obcaecati optio. Eaque, amet?
					</p>
					<p className='leading-8'>
						Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet
						quibusdam ab totam quia consequuntur officia maxime ratione tenetur,
						atque labore voluptatem harum quos voluptatum laudantium. Soluta,
						obcaecati optio. Eaque, amet?
					</p>
				</div>
				<div className='shadow-md text-center'>
					<form
						className='md:w-96 sm:text-center md:text-start'
						onSubmit={handleSubmit}>
						<label className='font-bold font-mono'>Your name</label>
						<br />
						<input
							type='text'
							placeholder='Jane Smith'
							className='p-2 border-2 md:w-96 outline-0 mb-4'
							value={names}
							onChange={(e) => setNames(e.target.value)}
						/>

						<br />
						<label className='font-bold font-mono'>Your email</label>
						<br />
						<input
							type='email'
							placeholder='janesmith@xxx.com'
							className='p-2 border-2 md:w-96 outline-0 mb-4'
							value={email}
							onChange={(e) => setEmail(e.target.value)}
						/>
						<br />

						<label className='font-bold font-mono'>Your message</label>
						<br />
						<textarea
							cols='30'
							rows='10'
							className='border-2 md:w-96 outline-0 resize-none'
							value={message}
							onChange={(e) => setMessage(e.target.value)}></textarea>
						<br />
						<div className='md:flex items-center justify-center'>
							<Link href='https://ijeonyi@gmail.com'>
								<button
									type='submit'
									className='bg-red-500 text-white p-4 rounded-lg outline-0 border-0 my-2'>
									send
								</button>
							</Link>
						</div>
					</form>
				</div>
			</section>
			<div className='flex items-center justify-end m-10'>
				<Link href='#'>
					<a>
						<Image src='/img/top.png' alt='top' width={50} height={50} />
					</a>
				</Link>
			</div>

			<Footer />
		</>
	);
}
