import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Navbar from '../comps/Navbar';
import Footer from '../comps/Footer';
import {useState}from 'react'

export default function Home() {
	const [names,setNames ]= useState('')
	return (
		<>
			<Head>
				<title>EatUp | Home </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<div className='container mx-auto mt-10 pb-8'>
				<div className='grid gap-6 lg:grid-cols-4'>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg'>
						<Image src='/img/1.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Abacha
							</h4>
							<p className='leading-8'>
								Abacha is an Eastern Nigeria dish made using dried, shredded
								cassava. You can eat it as a snack or a full meal.
							</p>
							<div className=' text-blue-600 underline pt-8 text-center'>
								<Link href='https://guardian.ng/life/how-to-make-abacha-african-salad-2/'>
									<a target='_blank'>Click to know info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg  '>
						<Image src='/img/2.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Chicken Curry sauce
							</h4>
							<p className='leading-8'>
								Nigerian Chicken Curry recipe is very easy to prepare, just a
								few ingredients and you’re ready to go.
							</p>
							<div className=' text-blue-600 underline pt-8 text-center'>
								<Link href='https://sisijemimah.com/2019/08/12/nigerian-chicken-curry-chicken-gravy-updated/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg '>
						<Image src='/img/3.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Macaroni
							</h4>
							<p className='leading-8'>
								Macaroni is dry pasta shaped like narrow tubes. Made with durum
								wheat, macaroni is commonly cut in short lengths.
							</p>
							<div className=' text-blue-600 underline pt-8 text-center'>
								<Link href='https://nkechiajaeroh.com/recipes/dinner/how-to-make-quick-and-easy-macaroni-jollof/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg '>
						<Image src='/img/4.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Fried-yam
							</h4>
							<p className='leading-8'>
								Fried yam is a popular street snack in Nigeria, it is commonly
								served with fried plantain and fried sauce.
							</p>
							<div className='text-blue-600 underline pt-8 text-center'>
								<Link href='https://www.myactivekitchen.com/2015410-fried-yam-recipe-and-fried-sauce/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg '>
						<Image src='/img/5.png' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Nkwobi
							</h4>
							<p className='leading-8'>
								Nkwobi is a traditional eastern Nigerian delicacy which is
								served mostly at restaurants.
							</p>
							<div className='text-blue-600 underline pt-8 text-center'>
								<Link href='https://www.thepretendchef.com/nkwobi-recipe/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg'>
						<Image src='/img/6.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Chicken and rice
							</h4>
							<p className='leading-8'>
								Chicken is a low fat, lean meat that can be used in many dishes.
								This recipe is full in flavour and healthy too.
							</p>
							<div className=' text-blue-600 underline pt-8 text-center'>
								<Link href='https://www.safefood.net/recipes/chicken-tomato-sauce-rice'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg '>
						<Image src='/img/7.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Chicken Salad
							</h4>
							<p className='leading-8'>
								Grilled Chicken Salad Recipe with Buttermilk Ranch Dressing is
								an easy summer salad recipe with so much flavor!
							</p>
							<div className=' text-blue-600 underline pt-8 text-center'>
								<Link href='https://sundaysuppermovement.com/grilled-chicken-salad/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
					<div className='bg-gray-200 p-8 rounded-lg shadow-lg'>
						<Image src='/img/8.jpg' alt='food' width={500} height={300} />
						<div>
							<h4 className='text-3xl text-center py-4 font-bold text-yellow-900'>
								Jollof Rice
							</h4>
							<p className='leading-8'>
								Jollof is quite easy to prepare and eaten by most people,jollof
								rice, is a rice dish from West Africa.
							</p>
							<div className=' text-blue-600 underline pt-8 text-center mb-4'>
								<Link href='https://www.allnigerianrecipes.com/rice/nigerian-jollof-rice/'>
									<a target='_blank'>Click for more info</a>
								</Link>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className='flex items-center justify-end m-10'>
				<Link href='#'>
					<a>
						<Image src='/img/top.png' alt='top' width={50} height={50} />
					</a>
				</Link>
			</div>

			<Footer />
		</>
	);
}
	